### ISSUE TITLE
fix for regression #316 reveals a possible segfault itriggered by DCD test suite

### ISSUE THREAD

**Issue by BBasile** [dlang-community/libdparse#318]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000859918 in _D6dparse6parser6Parser22parseStructInitializerMFZCQBx3ast17StructInitializer (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d:5688
5688            node.startLocation = a.index;
Missing separate debuginfos, use: dnf debuginfo-install libgcc-8.2.1-4.fc28.x86_64
(gdb) 
(gdb) bt
#0  0x0000000000859918 in _D6dparse6parser6Parser22parseStructInitializerMFZCQBx3ast17StructInitializer (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d:5688
#1  0x0000000000856b64 in _D6dparse6parser6Parser23parseNonVoidInitializerMFZCQBy3ast18NonVoidInitializer (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d:4461
#2  0x0000000000855802 in _D6dparse6parser6Parser16parseInitializerMFZCQBr3ast11Initializer (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d-mixin-3919:3919
#3  0x000000000084e554 in _D6dparse6parser6Parser24parseAutoDeclarationPartMFZCQBz3ast19AutoDeclarationPart (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d-mixin-1232:1232
#4  0x000000000084e389 in _D6dparse6parser6Parser20parseAutoDeclarationMFZCQBv3ast15AutoDeclaration (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d:1203
#5  0x000000000085c7e2 in _D6dparse6parser6Parser24parseVariableDeclarationMFCQBy3ast4TypebZCQCnQp19VariableDeclaration (this=0x7fffffffcf98, isAuto=true, 
    type=0x0) at libdparse/src/dparse/parser.d-mixin-6946:6946
#6  0x000000000085003c in _D6dparse6parser6Parser16parseDeclarationMFbbZCQBt3ast11Declaration (this=0x7fffffffcf98, mustBeDeclaration=false, strict=true)
    at libdparse/src/dparse/parser.d-mixin-1981:1981
#7  0x00000000008515ce in _D6dparse6parser6Parser27parseDeclarationOrStatementMFZCQCc3ast22DeclarationOrStatement (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d:2289
#8  0x0000000000851483 in _D6dparse6parser6Parser30parseDeclarationsAndStatementsMFbZCQCg3ast25DeclarationsAndStatements (this=0x7fffffffcf98, 
    includeCases=true) at libdparse/src/dparse/parser.d:2260
#9  0x000000000084e5db in _D6dparse6parser6Parser19parseBlockStatementMFZCQBu3ast14BlockStatement (this=0x7fffffffcf98)
    at libdparse/src/dparse/parser.d-mixin-1252:1252
#10 0x00000000007ff253 in dsymbol.conversion.AutocompleteParser.parseBlockStatement() (this=0x7fffffffcf98) at dsymbol/src/dsymbol/conversion/package.d:128
#11 0x000000000085873f in _D6dparse6parser6Parser26parseSpecifiedFunctionBodyMFZCQCb3ast21SpecifiedFunctionBody (this=0x7fffffffcf98)
---Type <return> to continue, or q <return> to quit---

```

**Comment by BBasile** [comment]
DCD tc20 led to parse a struct initializer because assign expression is not finsihed but since the init doesn't start with a curly brace, there's no need to start parsing a struct init at all.
